# Generated by Django 3.2.4 on 2021-06-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category'], 'verbose_name': 'Sub Categoria', 'verbose_name_plural': 'Sub Categorias'},
        ),
    ]
